name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6.2
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install requests redis

      - name: Run Unit Tests
        run: |
          export REDIS_HOST=localhost
          export REDIS_PORT=6379
          pytest tests/unit/

      - name: Run Integration Tests
        run: |
          export REDIS_HOST=localhost
          export REDIS_PORT=6379
          pytest tests/integration/

      - name: Run Others Tests
        run: |
          export REDIS_HOST=localhost
          export REDIS_PORT=6379
          pytest tests/other/